# XDC constraints for the Xilinx KC705 board
# part: xc7k325tffg900-2

# General configuration
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 2.5 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]


# set_max_delay 40 -datapath_only -from [get_clocks clk_mmcm_out] -to [get_clocks dac1_dco_clk]
# set_max_delay 40 -datapath_only -from [get_clocks clk_mmcm_out] -to [get_clocks dac2_dco_clk]

# System clocks
# 200 MHz
set_property -dict {LOC AD12 IOSTANDARD LVDS} [get_ports CLK_200MHZ_P]
set_property -dict {LOC AD11 IOSTANDARD LVDS} [get_ports CLK_200MHZ_N]
create_clock -period 5.000 -name clk_200mhz [get_ports CLK_200MHZ_P]

# LEDs
set_property -dict {LOC AB8 IOSTANDARD LVCMOS15 SLEW SLOW DRIVE 12} [get_ports {LED[0]}]
set_property -dict {LOC AA8 IOSTANDARD LVCMOS15 SLEW SLOW DRIVE 12} [get_ports {LED[1]}]
set_property -dict {LOC AC9 IOSTANDARD LVCMOS15 SLEW SLOW DRIVE 12} [get_ports {LED[2]}]
set_property -dict {LOC AB9 IOSTANDARD LVCMOS15 SLEW SLOW DRIVE 12} [get_ports {LED[3]}]
set_property -dict {LOC AE26 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports {LED[4]}]
set_property -dict {LOC G19 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports {LED[5]}]
set_property -dict {LOC E18 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports {LED[6]}]
set_property -dict {LOC F16 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports {LED[7]}]

set_false_path -to [get_ports {LED[*]}]
set_output_delay 0.000 [get_ports {LED[*]}]

# Reset button
set_property -dict {LOC AB7 IOSTANDARD LVCMOS15} [get_ports RESET]

set_false_path -from [get_ports RESET]
set_input_delay 0.000 [get_ports RESET]

# Push buttons
set_property -dict {LOC AA12 IOSTANDARD LVCMOS15} [get_ports BTNU]
set_property -dict {LOC AC6 IOSTANDARD LVCMOS15} [get_ports BTNL]
set_property -dict {LOC AB12 IOSTANDARD LVCMOS15} [get_ports BTND]
set_property -dict {LOC AG5 IOSTANDARD LVCMOS15} [get_ports BTNR]
set_property -dict {LOC G12 IOSTANDARD LVCMOS25} [get_ports BTNC]

set_false_path -from [get_ports {BTNU BTNL BTND BTNR BTNC}]
set_input_delay 0.000 [get_ports {BTNU BTNL BTND BTNR BTNC}]

# Toggle switches
set_property -dict {LOC Y29 IOSTANDARD LVCMOS25} [get_ports {SW[0]}]
set_property -dict {LOC W29 IOSTANDARD LVCMOS25} [get_ports {SW[1]}]
set_property -dict {LOC AA28 IOSTANDARD LVCMOS25} [get_ports {SW[2]}]
set_property -dict {LOC Y28 IOSTANDARD LVCMOS25} [get_ports {SW[3]}]

set_false_path -from [get_ports {SW[*]}]
set_input_delay 0.000 [get_ports {SW[*]}]

# UART
set_property -dict {LOC K24 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports UART_TXD]
set_property -dict {LOC M19 IOSTANDARD LVCMOS25} [get_ports UART_RXD]
set_property -dict {LOC L27 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports UART_RTS]
set_property -dict {LOC K23 IOSTANDARD LVCMOS25} [get_ports UART_CTS]

set_false_path -to [get_ports {UART_TXD UART_RTS}]
set_output_delay 0.000 [get_ports {UART_TXD UART_RTS}]
set_false_path -from [get_ports {UART_RXD UART_CTS}]
set_input_delay 0.000 [get_ports {UART_RXD UART_CTS}]

# Gigabit Ethernet GMII PHY
set_property -dict {LOC U27 IOSTANDARD LVCMOS25} [get_ports PHY_RX_CLK]
set_property -dict {LOC U30 IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[0]}]
set_property -dict {LOC U25 IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[1]}]
set_property -dict {LOC T25 IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[2]}]
set_property -dict {LOC U28 IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[3]}]
#set_property -dict {LOC R19  IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[4]}] ;# from U37.C4 RXD4
#set_property -dict {LOC T27  IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[5]}] ;# from U37.A1 RXD5
#set_property -dict {LOC T26  IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[6]}] ;# from U37.A2 RXD6
#set_property -dict {LOC T28  IOSTANDARD LVCMOS25} [get_ports {PHY_RXD[7]}] ;# from U37.C5 RXD7
set_property -dict {LOC R28 IOSTANDARD LVCMOS25} [get_ports PHY_RX_CTL]
#set_property -dict {LOC V26  IOSTANDARD LVCMOS25} [get_ports PHY_RX_ER] ;# from U37.D4 RXER
set_property -dict {LOC K30 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports PHY_TX_CLK]
#set_property -dict {LOC M28  IOSTANDARD LVCMOS25} [get_ports PHY_TX_CLK] ;# from U37.D1 TXCLK
set_property -dict {LOC N27 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[0]}]
set_property -dict {LOC N25 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[1]}]
set_property -dict {LOC M29 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[2]}]
set_property -dict {LOC L28 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[3]}]
#set_property -dict {LOC J26  IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[4]}] ;# from U37.H2 TXD4
#set_property -dict {LOC K26  IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[5]}] ;# from U37.H3 TXD5
#set_property -dict {LOC L30  IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[6]}] ;# from U37.J1 TXD6
#set_property -dict {LOC J28  IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports {PHY_TXD[7]}] ;# from U37.J2 TXD7
set_property -dict {LOC M27 IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports PHY_TX_CTL]
#set_property -dict {LOC N29  IOSTANDARD LVCMOS25 SLEW FAST DRIVE 16} [get_ports PHY_TX_ER] ;# from U37.F2 TXER
#set_property -dict {LOC A7   } [get_ports PHY_SGMII_RX_P] ;# MGTXRXP1_117 GTXE2_CHANNEL_X0Y9 / GTXE2_COMMON_X?Y? from U37.A7 SOUT_P
#set_property -dict {LOC A8   } [get_ports PHY_SGMII_RX_N] ;# MGTXRXN1_117 GTXE2_CHANNEL_X0Y9 / GTXE2_COMMON_X?Y? from U37.A8 SOUT_N
#set_property -dict {LOC A3   } [get_ports PHY_SGMII_TX_P] ;# MGTXTXP1_117 GTXE2_CHANNEL_X0Y9 / GTXE2_COMMON_X?Y? from U37.A3 SIN_P
#set_property -dict {LOC A4   } [get_ports PHY_SGMII_TX_N] ;# MGTXTXN1_117 GTXE2_CHANNEL_X0Y9 / GTXE2_COMMON_X?Y? from U37.A4 SIN_N
#set_property -dict {LOC G8   } [get_ports PHY_SGMII_CLK_P] ;# MGTREFCLK0P_117 from U2.7
#set_property -dict {LOC G7   } [get_ports PHY_SGMII_CLK_N] ;# MGTREFCLK0N_117 from U2.6
set_property -dict {LOC L20 IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports PHY_RESET_N]
set_property -dict {LOC N30 IOSTANDARD LVCMOS25} [get_ports PHY_INT_N]
#set_property -dict {LOC J21  IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports PHY_MDIO] ;# from U37.M1 MDIO
#set_property -dict {LOC R23  IOSTANDARD LVCMOS25 SLEW SLOW DRIVE 12} [get_ports PHY_MDC] ;# from U37.L3 MDC

#create_clock -period 40.000 -name phy_tx_clk [get_ports PHY_TX_CLK]
create_clock -period 8.000 -name phy_rx_clk [get_ports PHY_RX_CLK]
#create_clock -period 8.000 -name phy_sgmii_clk [get_ports PHY_SGMII_CLK_P]

set_false_path -to [get_ports PHY_RESET_N]
set_output_delay 0.000 [get_ports PHY_RESET_N]
set_false_path -from [get_ports PHY_INT_N]
set_input_delay 0.000 [get_ports PHY_INT_N]

#set_false_path -to [get_ports {PHY_MDIO PHY_MDC}]
#set_output_delay 0 [get_ports {PHY_MDIO PHY_MDC}]
#set_false_path -from [get_ports {PHY_MDIO}]
#set_input_delay 0 [get_ports {PHY_MDIO}]


set_property PACKAGE_PIN AH29 [get_ports SPI_SCLK]
set_property PACKAGE_PIN AG23 [get_ports SPI_SDIO]
set_property PACKAGE_PIN AF22 [get_ports SPI_SDO]
set_property PACKAGE_PIN AG29 [get_ports CLK_SPI_CE]
set_property PACKAGE_PIN AF26 [get_ports DAC1_SPI_CE]
set_property PACKAGE_PIN AF27 [get_ports DAC2_SPI_CE]

set_property IOSTANDARD LVCMOS25 [get_ports SPI_SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_SDIO]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_SDO]
set_property IOSTANDARD LVCMOS25 [get_ports CLK_SPI_CE]
set_property IOSTANDARD LVCMOS25 [get_ports DAC1_SPI_CE]
set_property IOSTANDARD LVCMOS25 [get_ports DAC2_SPI_CE]


set_property IOSTANDARD LVDS_25 [get_ports {DAC1_DATA_P[*]}]
set_property IOSTANDARD LVDS_25 [get_ports DAC1_DCI_P]
set_property IOSTANDARD LVDS_25 [get_ports DAC1_DCI_N]
set_property IOSTANDARD LVDS_25 [get_ports DAC1_DCO_P]
set_property IOSTANDARD LVDS_25 [get_ports DAC1_DCO_N]
# Reference-style debug build: leave DAC DCO unconstrained like the Alinx examples.
create_clock -period 4.000 -name dac1_dco_clk [get_ports DAC1_DCO_P]

set_property PACKAGE_PIN AE23 [get_ports DAC1_DCI_P]
set_property PACKAGE_PIN AD23 [get_ports DAC1_DCO_P]
set_property PACKAGE_PIN AC22 [get_ports {DAC1_DATA_P[0]}]
set_property PACKAGE_PIN AD21 [get_ports {DAC1_DATA_P[1]}]
set_property PACKAGE_PIN AC24 [get_ports {DAC1_DATA_P[2]}]
set_property PACKAGE_PIN AB24 [get_ports {DAC1_DATA_P[3]}]
set_property PACKAGE_PIN AE25 [get_ports {DAC1_DATA_P[4]}]
set_property PACKAGE_PIN AA20 [get_ports {DAC1_DATA_P[5]}]
set_property PACKAGE_PIN AJ24 [get_ports {DAC1_DATA_P[6]}]
set_property PACKAGE_PIN AK23 [get_ports {DAC1_DATA_P[7]}]
set_property PACKAGE_PIN AG25 [get_ports {DAC1_DATA_P[8]}]
set_property PACKAGE_PIN AJ22 [get_ports {DAC1_DATA_P[9]}]
set_property PACKAGE_PIN AG22 [get_ports {DAC1_DATA_P[10]}]
set_property PACKAGE_PIN AH21 [get_ports {DAC1_DATA_P[11]}]
set_property PACKAGE_PIN AG20 [get_ports {DAC1_DATA_P[12]}]
set_property PACKAGE_PIN AK20 [get_ports {DAC1_DATA_P[13]}]

set_property IOSTANDARD LVDS_25 [get_ports {DAC2_DATA_P[*]}]
set_property IOSTANDARD LVDS_25 [get_ports DAC2_DCI_P]
set_property IOSTANDARD LVDS_25 [get_ports DAC2_DCI_N]
set_property IOSTANDARD LVDS_25 [get_ports DAC2_DCO_P]
set_property IOSTANDARD LVDS_25 [get_ports DAC2_DCO_N]
create_clock -period 4.000 -name dac2_dco_clk [get_ports DAC2_DCO_P]

# DAC DCO clocks come from external source and are not phase-related to FPGA MMCM clocks.
# Also treat DAC1 and DAC2 DCO as asynchronous to each other.
# set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks clk_200mhz] -group [get_clocks dac1_dco_clk] -group [get_clocks dac2_dco_clk]

set_property PACKAGE_PIN AD27 [get_ports DAC2_DCI_P]
set_property PACKAGE_PIN AB27 [get_ports DAC2_DCO_P]
set_property PACKAGE_PIN AB29 [get_ports {DAC2_DATA_P[0]}]
set_property PACKAGE_PIN Y30 [get_ports {DAC2_DATA_P[1]}]
set_property PACKAGE_PIN AC29 [get_ports {DAC2_DATA_P[2]}]
set_property PACKAGE_PIN AD29 [get_ports {DAC2_DATA_P[3]}]
set_property PACKAGE_PIN AE30 [get_ports {DAC2_DATA_P[4]}]
set_property PACKAGE_PIN AE28 [get_ports {DAC2_DATA_P[5]}]
set_property PACKAGE_PIN AJ28 [get_ports {DAC2_DATA_P[6]}]
set_property PACKAGE_PIN AG30 [get_ports {DAC2_DATA_P[7]}]
set_property PACKAGE_PIN AC26 [get_ports {DAC2_DATA_P[8]}]
set_property PACKAGE_PIN AK29 [get_ports {DAC2_DATA_P[9]}]
set_property PACKAGE_PIN AG27 [get_ports {DAC2_DATA_P[10]}]
set_property PACKAGE_PIN AJ27 [get_ports {DAC2_DATA_P[11]}]
set_property PACKAGE_PIN AH26 [get_ports {DAC2_DATA_P[12]}]
set_property PACKAGE_PIN AJ26 [get_ports {DAC2_DATA_P[13]}]


# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA16_P]
# set_property PACKAGE_PIN A27 [get_ports FMC_HPC_LA16_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA16_N]
# set_property PACKAGE_PIN C24 [get_ports FMC_HPC_LA15_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA15_P]
# set_property PACKAGE_PIN B24 [get_ports FMC_HPC_LA15_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA15_N]
# set_property PACKAGE_PIN B28 [get_ports FMC_HPC_LA14_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA14_P]
# set_property PACKAGE_PIN A28 [get_ports FMC_HPC_LA14_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA14_N]
# set_property PACKAGE_PIN A25 [get_ports FMC_HPC_LA13_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA13_P]
# set_property PACKAGE_PIN A26 [get_ports FMC_HPC_LA13_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA13_N]
# set_property PACKAGE_PIN D26 [get_ports FMC_HPC_LA01_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA01_CC_P]
# set_property PACKAGE_PIN C26 [get_ports FMC_HPC_LA01_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA01_CC_N]
# set_property PACKAGE_PIN C25 [get_ports FMC_HPC_LA00_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA00_CC_P]
# set_property PACKAGE_PIN B25 [get_ports FMC_HPC_LA00_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA00_CC_N]
# set_property PACKAGE_PIN D27 [get_ports FMC_HPC_CLK0_M2C_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_CLK0_M2C_P]
# set_property PACKAGE_PIN C27 [get_ports FMC_HPC_CLK0_M2C_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_CLK0_M2C_N]
# set_property PACKAGE_PIN E28 [get_ports FMC_HPC_LA07_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA07_P]
# set_property PACKAGE_PIN D28 [get_ports FMC_HPC_LA07_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA07_N]
# set_property PACKAGE_PIN C29 [get_ports FMC_HPC_LA12_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA12_P]
# set_property PACKAGE_PIN B29 [get_ports FMC_HPC_LA12_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA12_N]
# set_property PACKAGE_PIN D29 [get_ports FMC_HPC_LA10_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA10_P]
# set_property PACKAGE_PIN C30 [get_ports FMC_HPC_LA10_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA10_N]
# set_property PACKAGE_PIN B30 [get_ports FMC_HPC_LA09_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA09_P]
# set_property PACKAGE_PIN A30 [get_ports FMC_HPC_LA09_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA09_N]
# set_property PACKAGE_PIN E29 [get_ports FMC_HPC_LA08_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA08_P]
# set_property PACKAGE_PIN E30 [get_ports FMC_HPC_LA08_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA08_N]
# set_property PACKAGE_PIN H24 [get_ports FMC_HPC_LA02_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA02_P]
# set_property PACKAGE_PIN H25 [get_ports FMC_HPC_LA02_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA02_N]
# set_property PACKAGE_PIN G28 [get_ports FMC_HPC_LA04_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA04_P]
# set_property PACKAGE_PIN F28 [get_ports FMC_HPC_LA04_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA04_N]
# set_property PACKAGE_PIN G27 [get_ports FMC_HPC_LA11_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA11_P]
# set_property PACKAGE_PIN F27 [get_ports FMC_HPC_LA11_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA11_N]
# set_property PACKAGE_PIN G29 [get_ports FMC_HPC_LA05_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA05_P]
# set_property PACKAGE_PIN F30 [get_ports FMC_HPC_LA05_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA05_N]
# set_property PACKAGE_PIN H26 [get_ports FMC_HPC_LA03_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA03_P]
# set_property PACKAGE_PIN H27 [get_ports FMC_HPC_LA03_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA03_N]
# set_property PACKAGE_PIN H30 [get_ports FMC_HPC_LA06_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA06_P]
# set_property PACKAGE_PIN G30 [get_ports FMC_HPC_LA06_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA06_N]
# set_property PACKAGE_PIN H21 [get_ports FMC_HPC_LA33_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA33_P]
# set_property PACKAGE_PIN H22 [get_ports FMC_HPC_LA33_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA33_N]
# set_property PACKAGE_PIN D21 [get_ports FMC_HPC_LA32_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA32_P]
# set_property PACKAGE_PIN C21 [get_ports FMC_HPC_LA32_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA32_N]
# set_property PACKAGE_PIN G22 [get_ports FMC_HPC_LA31_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA31_P]
# set_property PACKAGE_PIN F22 [get_ports FMC_HPC_LA31_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA31_N]
# set_property PACKAGE_PIN D22 [get_ports FMC_HPC_LA30_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA30_P]
# set_property PACKAGE_PIN C22 [get_ports FMC_HPC_LA30_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA30_N]
# set_property PACKAGE_PIN F21 [get_ports FMC_HPC_LA18_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA18_CC_P]
# set_property PACKAGE_PIN E21 [get_ports FMC_HPC_LA18_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA18_CC_N]
# set_property PACKAGE_PIN F20 [get_ports FMC_HPC_LA17_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA17_CC_P]
# set_property PACKAGE_PIN E20 [get_ports FMC_HPC_LA17_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA17_CC_N]
# set_property PACKAGE_PIN D17 [get_ports FMC_HPC_CLK1_M2C_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_CLK1_M2C_P]
# set_property PACKAGE_PIN D18 [get_ports FMC_HPC_CLK1_M2C_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_CLK1_M2C_N]
# set_property PACKAGE_PIN E19 [get_ports FMC_HPC_LA20_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA20_P]
# set_property PACKAGE_PIN D19 [get_ports FMC_HPC_LA20_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA20_N]
# set_property PACKAGE_PIN D16 [get_ports FMC_HPC_LA28_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA28_P]
# set_property PACKAGE_PIN C16 [get_ports FMC_HPC_LA28_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA28_N]
# set_property PACKAGE_PIN G18 [get_ports FMC_HPC_LA19_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA19_P]
# set_property PACKAGE_PIN F18 [get_ports FMC_HPC_LA19_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA19_N]
# set_property PACKAGE_PIN C17 [get_ports FMC_HPC_LA29_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA29_P]
# set_property PACKAGE_PIN B17 [get_ports FMC_HPC_LA29_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA29_N]
# set_property PACKAGE_PIN G17 [get_ports FMC_HPC_LA25_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA25_P]
# set_property PACKAGE_PIN F17 [get_ports FMC_HPC_LA25_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA25_N]
# set_property PACKAGE_PIN C20 [get_ports FMC_HPC_LA22_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA22_P]
# set_property PACKAGE_PIN B20 [get_ports FMC_HPC_LA22_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA22_N]
# set_property PACKAGE_PIN A16 [get_ports FMC_HPC_LA24_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA24_P]
# set_property PACKAGE_PIN A17 [get_ports FMC_HPC_LA24_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA24_N]
# set_property PACKAGE_PIN A20 [get_ports FMC_HPC_LA21_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA21_P]
# set_property PACKAGE_PIN A21 [get_ports FMC_HPC_LA21_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA21_N]
# set_property PACKAGE_PIN B18 [get_ports FMC_HPC_LA26_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA26_P]
# set_property PACKAGE_PIN A18 [get_ports FMC_HPC_LA26_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA26_N]
# set_property PACKAGE_PIN B22 [get_ports FMC_HPC_LA23_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA23_P]
# set_property PACKAGE_PIN A22 [get_ports FMC_HPC_LA23_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA23_N]
# set_property PACKAGE_PIN C19 [get_ports FMC_HPC_LA27_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA27_P]
# set_property PACKAGE_PIN B19 [get_ports FMC_HPC_LA27_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_LA27_N]
# set_property PACKAGE_PIN L16 [get_ports FMC_HPC_HA13_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA13_P]
# set_property PACKAGE_PIN K16 [get_ports FMC_HPC_HA13_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA13_N]
# set_property PACKAGE_PIN L15 [get_ports FMC_HPC_HA16_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA16_P]
# set_property PACKAGE_PIN K15 [get_ports FMC_HPC_HA16_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA16_N]
# set_property PACKAGE_PIN L12 [get_ports FMC_HPC_HA23_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA23_P]
# set_property PACKAGE_PIN L13 [get_ports FMC_HPC_HA23_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA23_N]
# set_property PACKAGE_PIN K13 [get_ports FMC_HPC_HA20_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA20_P]
# set_property PACKAGE_PIN J13 [get_ports FMC_HPC_HA20_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA20_N]
# set_property PACKAGE_PIN K14 [get_ports FMC_HPC_HA18_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA18_P]
# set_property PACKAGE_PIN J14 [get_ports FMC_HPC_HA18_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA18_N]
# set_property PACKAGE_PIN L11 [get_ports FMC_HPC_HA22_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA22_P]
# set_property PACKAGE_PIN K11 [get_ports FMC_HPC_HA22_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA22_N]
# set_property PACKAGE_PIN H15 [get_ports FMC_HPC_HA15_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA15_P]
# set_property PACKAGE_PIN G15 [get_ports FMC_HPC_HA15_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA15_N]
# set_property PACKAGE_PIN J11 [get_ports FMC_HPC_HA21_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA21_P]
# set_property PACKAGE_PIN J12 [get_ports FMC_HPC_HA21_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA21_N]
# set_property PACKAGE_PIN J16 [get_ports FMC_HPC_HA14_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA14_P]
# set_property PACKAGE_PIN H16 [get_ports FMC_HPC_HA14_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA14_N]
# set_property PACKAGE_PIN H11 [get_ports FMC_HPC_HA19_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA19_P]
# set_property PACKAGE_PIN H12 [get_ports FMC_HPC_HA19_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA19_N]
# set_property PACKAGE_PIN H14 [get_ports FMC_HPC_HA01_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA01_CC_P]
# set_property PACKAGE_PIN G14 [get_ports FMC_HPC_HA01_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA01_CC_N]
# set_property PACKAGE_PIN G13 [get_ports FMC_HPC_HA17_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA17_CC_P]
# set_property PACKAGE_PIN F13 [get_ports FMC_HPC_HA17_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA17_CC_N]
# set_property PACKAGE_PIN D12 [get_ports FMC_HPC_HA00_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA00_CC_P]
# set_property PACKAGE_PIN D13 [get_ports FMC_HPC_HA00_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA00_CC_N]
# set_property PACKAGE_PIN F12 [get_ports FMC_HPC_HA09_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA09_P]
# set_property PACKAGE_PIN E13 [get_ports FMC_HPC_HA09_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA09_N]
# set_property PACKAGE_PIN C12 [get_ports FMC_HPC_HA03_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA03_P]
# set_property PACKAGE_PIN B12 [get_ports FMC_HPC_HA03_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA03_N]
# set_property PACKAGE_PIN F11 [get_ports FMC_HPC_HA04_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA04_P]
# set_property PACKAGE_PIN E11 [get_ports FMC_HPC_HA04_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA04_N]
# set_property PACKAGE_PIN A11 [get_ports FMC_HPC_HA10_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA10_P]
# set_property PACKAGE_PIN A12 [get_ports FMC_HPC_HA10_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA10_N]
# set_property PACKAGE_PIN D11 [get_ports FMC_HPC_HA02_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA02_P]
# set_property PACKAGE_PIN C11 [get_ports FMC_HPC_HA02_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA02_N]
# set_property PACKAGE_PIN F15 [get_ports FMC_HPC_HA05_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA05_P]
# set_property PACKAGE_PIN E16 [get_ports FMC_HPC_HA05_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA05_N]
# set_property PACKAGE_PIN E14 [get_ports FMC_HPC_HA08_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA08_P]
# set_property PACKAGE_PIN E15 [get_ports FMC_HPC_HA08_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA08_N]
# set_property PACKAGE_PIN D14 [get_ports FMC_HPC_HA06_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA06_P]
# set_property PACKAGE_PIN C14 [get_ports FMC_HPC_HA06_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA06_N]
# set_property PACKAGE_PIN B13 [get_ports FMC_HPC_HA11_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA11_P]
# set_property PACKAGE_PIN A13 [get_ports FMC_HPC_HA11_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA11_N]
# set_property PACKAGE_PIN C15 [get_ports FMC_HPC_HA12_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA12_P]
# set_property PACKAGE_PIN B15 [get_ports FMC_HPC_HA12_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA12_N]
# set_property PACKAGE_PIN B14 [get_ports FMC_HPC_HA07_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA07_P]
# set_property PACKAGE_PIN A15 [get_ports FMC_HPC_HA07_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_HPC_HA07_N]


# set_property PACKAGE_PIN AA20 [get_ports FMC_LPC_LA12_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA12_P]
# set_property PACKAGE_PIN AB20 [get_ports FMC_LPC_LA12_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA12_N]
# set_property PACKAGE_PIN AB24 [get_ports FMC_LPC_LA13_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA13_P]
# set_property PACKAGE_PIN AC25 [get_ports FMC_LPC_LA13_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA13_N]
# set_property PACKAGE_PIN AC22 [get_ports FMC_LPC_LA16_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA16_P]
# set_property PACKAGE_PIN AD22 [get_ports FMC_LPC_LA16_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA16_N]
# set_property PACKAGE_PIN AC24 [get_ports FMC_LPC_LA15_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA15_P]
# set_property PACKAGE_PIN AD24 [get_ports FMC_LPC_LA15_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA15_N]
# set_property PACKAGE_PIN AD21 [get_ports FMC_LPC_LA14_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA14_P]
# set_property PACKAGE_PIN AE21 [get_ports FMC_LPC_LA14_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA14_N]
# set_property PACKAGE_PIN AE23 [get_ports FMC_LPC_LA01_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA01_CC_P]
# set_property PACKAGE_PIN AF23 [get_ports FMC_LPC_LA01_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA01_CC_N]
# set_property PACKAGE_PIN AD23 [get_ports FMC_LPC_LA00_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA00_CC_P]
# set_property PACKAGE_PIN AE24 [get_ports FMC_LPC_LA00_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA00_CC_N]
# set_property PACKAGE_PIN AF22 [get_ports FMC_LPC_CLK0_M2C_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_CLK0_M2C_P]
# set_property PACKAGE_PIN AG23 [get_ports FMC_LPC_CLK0_M2C_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_CLK0_M2C_N]
# set_property PACKAGE_PIN AG24 [get_ports SI5326_INT_ALM_LS]
# set_property IOSTANDARD LVDS_25 [get_ports SI5326_INT_ALM_LS]
# set_property PACKAGE_PIN AH24 [get_ports HDMI_INT]
# set_property IOSTANDARD LVDS_25 [get_ports HDMI_INT]
# set_property PACKAGE_PIN AJ24 [get_ports FMC_LPC_LA10_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA10_P]
# set_property PACKAGE_PIN AK25 [get_ports FMC_LPC_LA10_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA10_N]
# set_property PACKAGE_PIN AE25 [get_ports FMC_LPC_LA11_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA11_P]
# set_property PACKAGE_PIN AF25 [get_ports FMC_LPC_LA11_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA11_N]
# set_property PACKAGE_PIN AK23 [get_ports FMC_LPC_LA09_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA09_P]
# set_property PACKAGE_PIN AK24 [get_ports FMC_LPC_LA09_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA09_N]
# set_property PACKAGE_PIN AG25 [get_ports FMC_LPC_LA07_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA07_P]
# set_property PACKAGE_PIN AH25 [get_ports FMC_LPC_LA07_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA07_N]
# set_property PACKAGE_PIN AF20 [get_ports FMC_LPC_LA02_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA02_P]
# set_property PACKAGE_PIN AF21 [get_ports FMC_LPC_LA02_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA02_N]
# set_property PACKAGE_PIN AG22 [get_ports FMC_LPC_LA05_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA05_P]
# set_property PACKAGE_PIN AH22 [get_ports FMC_LPC_LA05_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA05_N]
# set_property PACKAGE_PIN AJ22 [get_ports FMC_LPC_LA08_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA08_P]
# set_property PACKAGE_PIN AJ23 [get_ports FMC_LPC_LA08_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA08_N]
# set_property PACKAGE_PIN AG20 [get_ports FMC_LPC_LA03_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA03_P]
# set_property PACKAGE_PIN AH20 [get_ports FMC_LPC_LA03_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA03_N]
# set_property PACKAGE_PIN AH21 [get_ports FMC_LPC_LA04_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA04_P]
# set_property PACKAGE_PIN AJ21 [get_ports FMC_LPC_LA04_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA04_N]
# set_property PACKAGE_PIN AK20 [get_ports FMC_LPC_LA06_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA06_P]
# set_property PACKAGE_PIN AK21 [get_ports FMC_LPC_LA06_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA06_N]
# set_property PACKAGE_PIN AE20 [get_ports SI5326_RST_LS]
# set_property IOSTANDARD LVDS_25 [get_ports SI5326_RST_LS]
# set_property PACKAGE_PIN Y25 [get_ports ROTARY_INCB]
# set_property IOSTANDARD LVDS_25 [get_ports ROTARY_INCB]
# set_property PACKAGE_PIN Y26 [get_ports ROTARY_INCA]
# set_property IOSTANDARD LVDS_25 [get_ports ROTARY_INCA]
# set_property PACKAGE_PIN AA26 [get_ports ROTARY_PUSH]
# set_property IOSTANDARD LVDS_25 [get_ports ROTARY_PUSH]
# set_property PACKAGE_PIN W27 [get_ports REC_CLOCK_C_P]
# set_property IOSTANDARD LVDS_25 [get_ports REC_CLOCK_C_P]
# set_property PACKAGE_PIN W28 [get_ports REC_CLOCK_C_N]
# set_property IOSTANDARD LVDS_25 [get_ports REC_CLOCK_C_N]
# set_property PACKAGE_PIN Y28 [get_ports GPIO_DIP_SW3]
# set_property IOSTANDARD LVDS_25 [get_ports GPIO_DIP_SW3]
# set_property PACKAGE_PIN AA28 [get_ports GPIO_DIP_SW2]
# set_property IOSTANDARD LVDS_25 [get_ports GPIO_DIP_SW2]
# set_property PACKAGE_PIN W29 [get_ports GPIO_DIP_SW1]
# set_property IOSTANDARD LVDS_25 [get_ports GPIO_DIP_SW1]
# set_property PACKAGE_PIN Y29 [get_ports GPIO_DIP_SW0]
# set_property IOSTANDARD LVDS_25 [get_ports GPIO_DIP_SW0]
# set_property PACKAGE_PIN AA27 [get_ports XADC_GPIO_3]
# set_property IOSTANDARD LVDS_25 [get_ports XADC_GPIO_3]
# set_property PACKAGE_PIN AB28 [get_ports XADC_GPIO_2]
# set_property IOSTANDARD LVDS_25 [get_ports XADC_GPIO_2]
# set_property PACKAGE_PIN AA25 [get_ports XADC_GPIO_1]
# set_property IOSTANDARD LVDS_25 [get_ports XADC_GPIO_1]
# set_property PACKAGE_PIN AB25 [get_ports XADC_GPIO_0]
# set_property IOSTANDARD LVDS_25 [get_ports XADC_GPIO_0]
# set_property PACKAGE_PIN AC29 [get_ports FMC_LPC_LA33_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA33_P]
# set_property PACKAGE_PIN AC30 [get_ports FMC_LPC_LA33_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA33_N]
# set_property PACKAGE_PIN Y30 [get_ports FMC_LPC_LA32_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA32_P]
# set_property PACKAGE_PIN AA30 [get_ports FMC_LPC_LA32_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA32_N]
# set_property PACKAGE_PIN AD29 [get_ports FMC_LPC_LA31_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA31_P]
# set_property PACKAGE_PIN AE29 [get_ports FMC_LPC_LA31_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA31_N]
# set_property PACKAGE_PIN AB29 [get_ports FMC_LPC_LA30_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA30_P]
# set_property PACKAGE_PIN AB30 [get_ports FMC_LPC_LA30_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA30_N]
# set_property PACKAGE_PIN AD27 [get_ports FMC_LPC_LA18_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA18_CC_P]
# set_property PACKAGE_PIN AD28 [get_ports FMC_LPC_LA18_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA18_CC_N]
# set_property PACKAGE_PIN AB27 [get_ports FMC_LPC_LA17_CC_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA17_CC_P]
# set_property PACKAGE_PIN AC27 [get_ports FMC_LPC_LA17_CC_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA17_CC_N]
# set_property PACKAGE_PIN AG29 [get_ports FMC_LPC_CLK1_M2C_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_CLK1_M2C_P]
# set_property PACKAGE_PIN AH29 [get_ports FMC_LPC_CLK1_M2C_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_CLK1_M2C_N]
# set_property PACKAGE_PIN AE28 [get_ports FMC_LPC_LA29_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA29_P]
# set_property PACKAGE_PIN AF28 [get_ports FMC_LPC_LA29_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA29_N]
# set_property PACKAGE_PIN AK29 [get_ports FMC_LPC_LA26_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA26_P]
# set_property PACKAGE_PIN AK30 [get_ports FMC_LPC_LA26_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA26_N]
# set_property PACKAGE_PIN AE30 [get_ports FMC_LPC_LA28_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA28_P]
# set_property PACKAGE_PIN AF30 [get_ports FMC_LPC_LA28_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA28_N]
# set_property PACKAGE_PIN AJ28 [get_ports FMC_LPC_LA27_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA27_P]
# set_property PACKAGE_PIN AJ29 [get_ports FMC_LPC_LA27_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA27_N]
# set_property PACKAGE_PIN AG30 [get_ports FMC_LPC_LA24_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA24_P]
# set_property PACKAGE_PIN AH30 [get_ports FMC_LPC_LA24_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA24_N]
# set_property PACKAGE_PIN AC26 [get_ports FMC_LPC_LA25_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA25_P]
# set_property PACKAGE_PIN AD26 [get_ports FMC_LPC_LA25_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA25_N]
# set_property PACKAGE_PIN AJ27 [get_ports FMC_LPC_LA22_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA22_P]
# set_property PACKAGE_PIN AK28 [get_ports FMC_LPC_LA22_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA22_N]
# set_property PACKAGE_PIN AG27 [get_ports FMC_LPC_LA21_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA21_P]
# set_property PACKAGE_PIN AG28 [get_ports FMC_LPC_LA21_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA21_N]
# set_property PACKAGE_PIN AH26 [get_ports FMC_LPC_LA23_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA23_P]
# set_property PACKAGE_PIN AH27 [get_ports FMC_LPC_LA23_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA23_N]
# set_property PACKAGE_PIN AF26 [get_ports FMC_LPC_LA20_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA20_P]
# set_property PACKAGE_PIN AF27 [get_ports FMC_LPC_LA20_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA20_N]
# set_property PACKAGE_PIN AJ26 [get_ports FMC_LPC_LA19_P]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA19_P]
# set_property PACKAGE_PIN AK26 [get_ports FMC_LPC_LA19_N]
# set_property IOSTANDARD LVDS_25 [get_ports FMC_LPC_LA19_N]




connect_debug_port u_ila_0/probe0 [get_nets [list {dac1_l_debug[0]} {dac1_l_debug[1]} {dac1_l_debug[2]} {dac1_l_debug[3]} {dac1_l_debug[4]} {dac1_l_debug[5]} {dac1_l_debug[6]} {dac1_l_debug[7]} {dac1_l_debug[8]} {dac1_l_debug[9]} {dac1_l_debug[10]} {dac1_l_debug[11]} {dac1_l_debug[12]} {dac1_l_debug[13]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {dac1_h_debug[0]} {dac1_h_debug[1]} {dac1_h_debug[2]} {dac1_h_debug[3]} {dac1_h_debug[4]} {dac1_h_debug[5]} {dac1_h_debug[6]} {dac1_h_debug[7]} {dac1_h_debug[8]} {dac1_h_debug[9]} {dac1_h_debug[10]} {dac1_h_debug[11]} {dac1_h_debug[12]} {dac1_h_debug[13]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list dac_tone_mode_debug]]





